const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirtsiaici',
      category: ' shirts',
      image: '/images/p1.jpg',
      price: 120,
      countinstock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'nike-slim-shirtdarsiaici',
      category: ' shirts',
      image: '/images/p2.jpg',
      price: 120,
      countinstock: 20,
      brand: 'nike',
      rating: 2,
      numReviews: 3,
      description: 'High quality shirt',
    },
    {
      name: 'Pantof Slim Shirt',
      slug: 'nike-slim-shirtchiarsiaici',
      category: ' shirts',
      image: '/images/p3.jpg',
      price: 120,
      countinstock: 10,
      brand: 'nike',
      rating: 4,
      numReviews: 5,
      description: 'High quality shirt',
    },
    {
      name: 'Curea Slim Shirt',
      slug: 'nike-slim-shirtmaialesaici',
      category: ' shirts',
      image: '/images/p4.jpg',
      price: 120,
      countinstock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
  ],
};
export default data;
